#pragma once



#define CLIENT_TEXT					"Client"
#define CLIENT_REQUEST_TEXT			"CLIENT_REQUEST"
#define NO_LEADER_FOUND				-1 



#define SEMAPHORE_RECEIVE_LEADER	1
#define SEMAPHORE_COMMIT_VALUE		1
#define TIME_WAITING_A_LEADER		10000//(ms)
#define TIME_WAITING_COMMIT_VALUE	10000//(ms)

